apiVersion: v1
kind: Service
metadata:
  name: test-report-web
  labels:
    app: test-report-web
spec:
  ports:
    - port: 4040
      targetPort: 4040
      name: port0
      protocol: TCP
    - port: 5050
      targetPort: 5050
      name: port1
      protocol: TCP
  selector:
    app: test-report-web
  type: LoadBalancer
  sessionAffinity: None
