apiVersion: batch/v1
kind: Job
metadata:
  name: web-test-v$version
spec:
  template:
    spec:
      volumes:
        - name: test-report-web
          persistentVolumeClaim:
            claimName: test-report
      containers:
        - name: web-test-v$version
          image: abhimassive/allure:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: qa-config
          command: ["/bin/sh", "-c"]
          args:
            - echo START;
              yarn run web --spec test/web/specs/accounts/signInAndOutTest.js --browser:chrome_headless;
              allure generate allure-results --clean;
              cp -R allure-report/history/ allure-results/history/;
              cp -R allure-results/* /app;
              cd /app;
              ls -a;
              ls | wc -l;
              pwd;
              echo END;
          volumeMounts:
            - mountPath: /app
              name: test-report-web
      restartPolicy: Never
  backoffLimit: 1
  activeDeadlineSeconds: 1800
