apiVersion: v1
kind: ConfigMap
metadata:
  name: quota
  namespace: development
data:
  browsers.json: |
    {
      "chrome": {
          "default": "69.0",
          "versions": {
              "69.0": {
                  "image": "selenoid/vnc_chrome:69.0",
                  "port": "4444",
                  "path": "/"
              }
          }
      }
    }
