apiVersion: v1
kind: Service
metadata:
  name: selenoid-hub
  labels:
    app: selenoid-hub
spec:
  ports:
  - port: 4444 
    targetPort: 4444 
    name: port0
  selector:
    app: selenoid-hub
  type: NodePort
  sessionAffinity: None