apiVersion: v1
kind: Service
metadata:
  name: allure-service
  labels:
    app: allure-service
spec:
  ports:
    - port: 4040
      targetPort: 4040
      name: port0
      protocol: TCP
    - port: 5050
      targetPort: 5050
      name: port1
      protocol: TCP
  selector:
    app: allure
  type: LoadBalancer
  sessionAffinity: None
