kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: allure-claim-hostpath
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
