apiVersion: v1
kind: PersistentVolume
metadata:
  name: allure
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /app/allure-results
