apiVersion: batch/v1
kind: Job
metadata:
  name: web-smoke-test-copy
spec:
  template:
    spec:
      containers:
        - name: web-smoke-test-copy
          image: massiveinteractive/qa-ci:v181026-023937
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: qa-config

          command: ["/bin/sh", "-c"]
          args:
            - echo starting;
              NODE_ENV=production yarn run web --browser:ch;
              ls -a;
              echo done;
      restartPolicy: OnFailure
  backoffLimit: 1
  activeDeadlineSeconds: 300
