apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-automation 
  labels:
    app: qa-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qa-automation
  template:
    metadata:
      labels:
        app: qa-automation
    spec:
      containers:
      - name: qa-automation
        image: abhimassive/auto:test
        ports:
          - containerPort: 8080 
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        env:
        - name: WEB_DEV
          value: "https://appcurator.io"
        